import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import UsersComponent from "~/components/Users";
import SidebarComponent from "~/components/Sidebar";
import RivCalendar from "~/components/RivCalendar";
import ChargingSlotQueue from "~/components/ChargingSlotQueue";

export default function Home() {
  const { data: session, status } = useSession();
  const [selectedDate, setSelectedDate] = useState(null);
  const router = useRouter();

  useEffect(() => {
    if (status === "unauthenticated") {
      void router.push("/login");
    }
  }, [status, router]);

  if (status === "loading") {
    return <div>Loading...</div>;
  }

  if (!session) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="flex flex-col lg:flex-row min-h-screen">
        <SidebarComponent />

        <div className="flex flex-col lg:flex-row items-center justify-center flex-1">
          <div className="flex flex-col lg:ml-6 lg:mt-0 mt-6">
            <UsersComponent />
            {selectedDate && (
              <ChargingSlotQueue selectedDate={selectedDate} />
            )}
          </div>
          <RivCalendar onSlotSelect={setSelectedDate} />

        </div>
      </main>
    </>
  );
}
